version: '3'

services:
  postgres:
    #restart: always
    image: postgres:12.3
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres123
  parking:
    #restart: always
    build: .
    ports:
      - "8065:8080"
    links:
      - postgres:postgres
    depends_on:
      - postgres

volumes:
  pgdata: